### ISSUE TITLE
Pinokio stops the installation at 6/9

### ISSUE THREAD

**Issue by thecoulibaly** [6Morpheus6/pinokio-wiki#3]
Look for a dialog requesting admin permission and approve it to proceed. This will install Microsoft visual studio build tools, which is required for building several python wheels. Please, what is the way forward ? Thank you.

**Comment by 6Morpheus6** [comment]
@thecoulibaly  Sorry for the late reply. The solution is actually in the Wiki. :)
https://github.com/6Morpheus6/pinokio-wiki?tab=readme-ov-file#4-manually-install-visual-buildtools-2019-with-windows-powershell
